language: ruby

rvm:
  - 2.2.0
  - 2.1.0

env:
  - RAILS_VERSION=3.2.21
  - RAILS_VERSION=4.0.13
  - RAILS_VERSION=4.1.16
  - RAILS_VERSION=4.2.7

notifications:
  email:
    recipients:
      - thomas@webhippie.de
    on_success: change
    on_failure: always

  irc:
    channels:
      - "irc.freenode.net#webhippie"
    template:
      - "%{repository_slug} (%{commit}) : %{message} by %{author}"
      - "You can see details at %{build_url}"
    on_success: change
    on_failure: always
